### ISSUE TITLE
initial build error

### ISSUE THREAD

**Issue by ahnjinwoo** [glennw/miniservo-gtk#4]
I am so curious how miniservo looks like. But I cannot build it.

/subhome/ahnjinwoo/miniservo-gtk/src/main.cpp: In member function ‘void ServoTab::init(TabEventHandler_, GtkNotebook_)’:
/subhome/ahnjinwoo/miniservo-gtk/src/main.cpp:153:98: error: ‘gdk_screen_get_monitor_scale_factor’ was not declared in this scope
         mHiDpiScale = gdk_screen_get_monitor_scale_factor(GDK_SCREEN(gdk_screen_get_default()), 0);
                                                                                                  ^
make[2]: **\* [CMakeFiles/miniservo.dir/src/main.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[1]: **\* [CMakeFiles/miniservo.dir/all] Error 2
make: **\* [all] Error 2

**Comment by glennw** [comment]
This _might_ be because you're running an older version of GTK/GDK than required? I wonder when that interface was introduced.

In any case, miniservo is quite broken at the moment in other parts and I don't have time to maintain it at the moment sorry.

**Comment by ahnjinwoo** [comment]
Thank you for your response. Could you inform when was stable? I will use git reset --hard, so I can back to the stable version.
